#pragma once

#include <string>
#include <cstdlib>
#include "root_directory.h" // This is a configuration file generated by CMake.

class FileSystem {
public:
    static std::string GetPath(const std::string& path);

private:
    typedef std::string (*Builder) (const std::string& path);

    static std::string const & GetRoot();

    static Builder GetPathBuilder();

    static std::string GetPathRelativeRoot(const std::string& path);

    static std::string GetPathRelativeBinary(const std::string& path);
};
